### ISSUE TITLE
App crashes after rotation

### ISSUE THREAD

**Issue by KosunaKoizumi** [yanzm/BottomNavigationSample#1]
Process: net.yanzm.bottomnavigationsample, PID: 17420
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{net.yanzm.bottomnavigationsample/net.yanzm.bottomnavigationsample.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.design.widget.CustomBottomNavigationView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/bottom_navigation. Make sure other views do not use the same id.
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738)
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:135)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.design.widget.CustomBottomNavigationView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/bottom_navigation. Make sure other views do not use the same id.
                                                                                      at android.view.View.onRestoreInstanceState(View.java:12823)
                                                                                      at android.support.design.widget.CustomBottomNavigationView.onRestoreInstanceState(CustomBottomNavigationView.java:103)
                                                                                      at android.view.View.dispatchRestoreInstanceState(View.java:12799)
                                                                                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2637)
                                                                                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
                                                                                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
                                                                                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
                                                                                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
                                                                                      at android.view.View.restoreHierarchyState(View.java:12777)
                                                                                      at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1744)
                                                                                      at android.app.Activity.onRestoreInstanceState(Activity.java:944)
                                                                                      at android.app.Activity.performRestoreInstanceState(Activity.java:916)
                                                                                      at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738) 
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:135) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by yanzm** [comment]
Not happen. "Make sure other views do not use the same id. " as error message
